---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gynt.
--- DateTime: 12/12/2021 17:38
---


return {
    init = function(self, config)

    end,

    enable = function(self, config)

        --- Priest unit targeting improvement: only units who are walking to an area near the priest are selected.

        local infoLocation = core.AOBScan("b9 ? ? ? ? c1 fe 06 e8 ? ? ? ? 83 f8 28 7f 17 99 2b c2 d1 f8 f7 d8 03 f0 3b 74 24 10 7e 08 89 74 24 10 89 6c 24 14")

        ---This function does a rectangle based distance calculation
        local distanceFunction = core.readInteger(infoLocation + 9) + infoLocation + 8 + 5
        local distanceFunctionThis = core.readInteger(infoLocation + 1)

        local hookLocation = infoLocation + 18

        local returnLocation = hookLocation + 5

        local successLocation = hookLocation + 15
        local failLocation = hookLocation + 23

        local addedCode = [[

        push eax ; store the original result, because it is used later


        movsx ecx, word [EDI + 0xfffffe2A] ; targetY
        push ecx
        movsx ecx, word [EDI + 0xfffffe28] ; targetx
        push ecx
        mov ecx, dword [ESP + 0x18 + 0x0C] ; add 12 because three pushes done so far
        push ecx
        mov ecx, dword [ESP + 0x1c + 0x10] ; add 16 because four pushes done so far
        push ecx

        mov ecx, distanceFunctionThis
        call distanceFunction ; resulting distance is in eax

        cmp eax, 40
        pop eax ; restore original eax value

        jg failLocation ; unit target distance is too far away...

        ; originalCode

        cdq
        sub eax, edx
        sar eax, 1
        ; jmp returnLocation
        ]]

        core.insertCode(
                hookLocation,
                5,
                {core.AssemblyLambda(addedCode, {
                    distanceFunction = distanceFunction,
                    distanceFunctionThis = distanceFunctionThis,
                    failLocation = failLocation,
                    -- returnLocation = returnLocation
                })})
    end,

    disable = function(self, config)
        error("not implemented")
    end
}
