local AIPersonalityFieldsEnum = {
    "WallDecoration",
    "Unknown001",
    "Unknown002",
    "Unknown003",
    "Unknown004",
    "Unknown005",
    "CriticalPopularity",
    "LowestPopularity",
    "HighestPopularity",
    "TaxesMin",
    "TaxesMax",
    "Unknown011",
    "Farm1",
    "Farm2",
    "Farm3",
    "Farm4",
    "Farm5",
    "Farm6",
    "Farm7",
    "Farm8",
    "PopulationPerFarm",
    "PopulationPerWoodcutter",
    "PopulationPerQuarry",
    "PopulationPerIronmine",
    "PopulationPerPitchrig",
    "MaxQuarries",
    "MaxIronmines",
    "MaxWoodcutters",
    "MaxPitchrigs",
    "MaxFarms",
    "BuildInterval",
    "ResourceRebuildDelay",
    "MaxFood",
    "MinimumApples",
    "MinimumCheese",
    "MinimumBread",
    "MinimumWheat",
    "MinimumHop",
    "TradeAmountFood",
    "TradeAmountEquipment",
    "AIRequestDelay",
    "MinimumGoodsRequiredAfterTrade",
    "DoubleRationsFoodThreshold",
    "MaxWood",
    "MaxStone",
    "MaxResourceOther",
    "MaxEquipment",
    "MaxBeer",
    "MaxResourceVariance",
    "RecruitGoldThreshold",
    "BlacksmithSetting",
    "FletcherSetting",
    "PoleturnerSetting",
    "SellResource01",
    "SellResource02",
    "SellResource03",
    "SellResource04",
    "SellResource05",
    "SellResource06",
    "SellResource07",
    "SellResource08",
    "SellResource09",
    "SellResource10",
    "SellResource11",
    "SellResource12",
    "SellResource13",
    "SellResource14",
    "SellResource15",
    "DefWallPatrolRallyTime",
    "DefWallPatrolGroups",
    "DefSiegeEngineGoldThreshold",
    "DefSiegeEngineBuildDelay",
    "Unknown072",
    "Unknown073",
    "RecruitProbDefDefault",
    "RecruitProbDefWeak",
    "RecruitProbDefStrong",
    "RecruitProbRaidDefault",
    "RecruitProbRaidWeak",
    "RecruitProbRaidStrong",
    "RecruitProbAttackDefault",
    "RecruitProbAttackWeak",
    "RecruitProbAttackStrong",
    "SortieUnitRangedMin",
    "SortieUnitRanged",
    "SortieUnitMeleeMin",
    "SortieUnitMelee",
    "DefDiggingUnitMax",
    "DefDiggingUnit",
    "RecruitInterval",
    "RecruitIntervalWeak",
    "RecruitIntervalStrong",
    "DefTotal",
    "OuterPatrolGroupsCount",
    "OuterPatrolGroupsMove",
    "OuterPatrolRallyDelay",
    "DefWalls",
    "DefUnit1",
    "DefUnit2",
    "DefUnit3",
    "DefUnit4",
    "DefUnit5",
    "DefUnit6",
    "DefUnit7",
    "DefUnit8",
    "RaidUnitsBase",
    "RaidUnitsRandom",
    "RaidUnit1",
    "RaidUnit2",
    "RaidUnit3",
    "RaidUnit4",
    "RaidUnit5",
    "RaidUnit6",
    "RaidUnit7",
    "RaidUnit8",
    "HarassingSiegeEngine1",
    "HarassingSiegeEngine2",
    "HarassingSiegeEngine3",
    "HarassingSiegeEngine4",
    "HarassingSiegeEngine5",
    "HarassingSiegeEngine6",
    "HarassingSiegeEngine7",
    "HarassingSiegeEngine8",
    "HarassingSiegeEnginesMax",
    "RaidRetargetDelay",
    "AttForceBase",
    "AttForceRandom",
    "AttForceSupportAllyThreshold",
    "AttForceRallyPercentage",
    "Unknown129",
    "AttAssaultDelay",
    "AttUnitPatrolRecommandDelay",
    "Unknown132",
    "SiegeEngine1",
    "SiegeEngine2",
    "SiegeEngine3",
    "SiegeEngine4",
    "SiegeEngine5",
    "SiegeEngine6",
    "SiegeEngine7",
    "SiegeEngine8",
    "CowThrowInterval",
    "Unknown142",
    "AttMaxEngineers",
    "AttDiggingUnit",
    "AttDiggingUnitMax",
    "AttUnitVanguard",
    "AttUnitVanguardMax",
    "AttMaxAssassins",
    "AttMaxLaddermen",
    "AttMaxTunnelers",
    "AttUnitPatrol",
    "AttUnitPatrolMax",
    "AttUnitPatrolGroupsCount",
    "AttUnitBackup",
    "AttUnitBackupMax",
    "AttUnitBackupGroupsCount",
    "AttUnitEngage",
    "AttUnitEngageMax",
    "AttUnitSiegeDef",
    "AttUnitSiegeDefMax",
    "AttUnitSiegeDefGroupsCount",
    "AttUnitMain1",
    "AttUnitMain2",
    "AttUnitMain3",
    "AttUnitMain4",
    "AttMaxDefault",
    "AttMainGroupsCount",
    "TargetChoice"
}


local AIPersonalityFieldTypes = {
    WallDecoration = "integer",
    Unknown001 = "integer",
    Unknown002 = "integer",
    Unknown003 = "integer",
    Unknown004 = "integer",
    Unknown005 = "integer",
    CriticalPopularity = "integer",
    LowestPopularity = "integer",
    HighestPopularity = "integer",
    TaxesMin = "integer",
    TaxesMax = "integer",
    Unknown011 = "integer",
    Farm1 = "FarmBuildingEnum",
    Farm2 = "FarmBuildingEnum",
    Farm3 = "FarmBuildingEnum",
    Farm4 = "FarmBuildingEnum",
    Farm5 = "FarmBuildingEnum",
    Farm6 = "FarmBuildingEnum",
    Farm7 = "FarmBuildingEnum",
    Farm8 = "FarmBuildingEnum",
    PopulationPerFarm = "integer",
    PopulationPerWoodcutter = "integer",
    PopulationPerQuarry = "integer",
    PopulationPerIronmine = "integer",
    PopulationPerPitchrig = "integer",
    MaxQuarries = "integer",
    MaxIronmines = "integer",
    MaxWoodcutters = "integer",
    MaxPitchrigs = "integer",
    MaxFarms = "integer",
    BuildInterval = "integer",
    ResourceRebuildDelay = "integer",
    MaxFood = "integer",
    MinimumApples = "integer",
    MinimumCheese = "integer",
    MinimumBread = "integer",
    MinimumWheat = "integer",
    MinimumHop = "integer",
    TradeAmountFood = "integer",
    TradeAmountEquipment = "integer",
    AIRequestDelay = "integer",
    MinimumGoodsRequiredAfterTrade = "integer",
    DoubleRationsFoodThreshold = "integer",
    MaxWood = "integer",
    MaxStone = "integer",
    MaxResourceOther = "integer",
    MaxEquipment = "integer",
    MaxBeer = "integer",
    MaxResourceVariance = "integer",
    RecruitGoldThreshold = "integer",
    BlacksmithSetting = "BlacksmithSettingEnum",
    FletcherSetting = "FletcherSettingEnum",
    PoleturnerSetting = "PoleturnerSettingEnum",
    SellResource01 = "ResourceEnum",
    SellResource02 = "ResourceEnum",
    SellResource03 = "ResourceEnum",
    SellResource04 = "ResourceEnum",
    SellResource05 = "ResourceEnum",
    SellResource06 = "ResourceEnum",
    SellResource07 = "ResourceEnum",
    SellResource08 = "ResourceEnum",
    SellResource09 = "ResourceEnum",
    SellResource10 = "ResourceEnum",
    SellResource11 = "ResourceEnum",
    SellResource12 = "ResourceEnum",
    SellResource13 = "ResourceEnum",
    SellResource14 = "ResourceEnum",
    SellResource15 = "ResourceEnum",
    DefWallPatrolRallyTime = "integer",
    DefWallPatrolGroups = "integer",
    DefSiegeEngineGoldThreshold = "integer",
    DefSiegeEngineBuildDelay = "integer",
    Unknown072 = "integer",
    Unknown073 = "integer",
    RecruitProbDefDefault = "integer",
    RecruitProbDefWeak = "integer",
    RecruitProbDefStrong = "integer",
    RecruitProbRaidDefault = "integer",
    RecruitProbRaidWeak = "integer",
    RecruitProbRaidStrong = "integer",
    RecruitProbAttackDefault = "integer",
    RecruitProbAttackWeak = "integer",
    RecruitProbAttackStrong = "integer",
    SortieUnitRangedMin = "integer",
    SortieUnitRanged = "UnitEnum",
    SortieUnitMeleeMin = "integer",
    SortieUnitMelee = "UnitEnum",
    DefDiggingUnitMax = "integer",
    DefDiggingUnit = "UnitEnum",
    RecruitInterval = "integer",
    RecruitIntervalWeak = "integer",
    RecruitIntervalStrong = "integer",
    DefTotal = "integer",
    OuterPatrolGroupsCount = "integer",
    OuterPatrolGroupsMove = "boolean",
    OuterPatrolRallyDelay = "integer",
    DefWalls = "integer",
    DefUnit1 = "UnitEnum",
    DefUnit2 = "UnitEnum",
    DefUnit3 = "UnitEnum",
    DefUnit4 = "UnitEnum",
    DefUnit5 = "UnitEnum",
    DefUnit6 = "UnitEnum",
    DefUnit7 = "UnitEnum",
    DefUnit8 = "UnitEnum",
    RaidUnitsBase = "integer",
    RaidUnitsRandom = "integer",
    RaidUnit1 = "UnitEnum",
    RaidUnit2 = "UnitEnum",
    RaidUnit3 = "UnitEnum",
    RaidUnit4 = "UnitEnum",
    RaidUnit5 = "UnitEnum",
    RaidUnit6 = "UnitEnum",
    RaidUnit7 = "UnitEnum",
    RaidUnit8 = "UnitEnum",
    HarassingSiegeEngine1 = "UnitEnum",
    HarassingSiegeEngine2 = "UnitEnum",
    HarassingSiegeEngine3 = "UnitEnum",
    HarassingSiegeEngine4 = "UnitEnum",
    HarassingSiegeEngine5 = "UnitEnum",
    HarassingSiegeEngine6 = "UnitEnum",
    HarassingSiegeEngine7 = "UnitEnum",
    HarassingSiegeEngine8 = "UnitEnum",
    HarassingSiegeEnginesMax = "integer",
    RaidRetargetDelay = "integer",
    AttForceBase = "integer",
    AttForceRandom = "integer",
    AttForceSupportAllyThreshold = "integer",
    AttForceRallyPercentage = "integer",
    Unknown129 = "integer",
    AttAssaultDelay = "integer",
    AttUnitPatrolRecommandDelay = "integer",
    Unknown132 = "integer",
    SiegeEngine1 = "HarassingSiegeEngineEnum",
    SiegeEngine2 = "HarassingSiegeEngineEnum",
    SiegeEngine3 = "HarassingSiegeEngineEnum",
    SiegeEngine4 = "HarassingSiegeEngineEnum",
    SiegeEngine5 = "HarassingSiegeEngineEnum",
    SiegeEngine6 = "HarassingSiegeEngineEnum",
    SiegeEngine7 = "HarassingSiegeEngineEnum",
    SiegeEngine8 = "HarassingSiegeEngineEnum",
    CowThrowInterval = "integer",
    Unknown142 = "integer",
    AttMaxEngineers = "integer",
    AttDiggingUnit = "UnitEnum",
    AttDiggingUnitMax = "integer",
    AttUnitVanguard = "UnitEnum",
    AttUnitVanguardMax = "integer",
    AttMaxAssassins = "integer",
    AttMaxLaddermen = "integer",
    AttMaxTunnelers = "integer",
    AttUnitPatrol = "UnitEnum",
    AttUnitPatrolMax = "integer",
    AttUnitPatrolGroupsCount = "integer",
    AttUnitBackup = "UnitEnum",
    AttUnitBackupMax = "integer",
    AttUnitBackupGroupsCount = "integer",
    AttUnitEngage = "integer",
    AttUnitEngageMax = "integer",
    AttUnitSiegeDef = "UnitEnum",
    AttUnitSiegeDefMax = "integer",
    AttUnitSiegeDefGroupsCount = "integer",
    AttUnitMain1 = "UnitEnum",
    AttUnitMain2 = "UnitEnum",
    AttUnitMain3 = "UnitEnum",
    AttUnitMain4 = "UnitEnum",
    AttMaxDefault = "integer",
    AttMainGroupsCount = "integer",
    TargetChoice = "TargetingTypeEnum"
}

return AIPersonalityFieldsEnum, AIPersonalityFieldTypes