---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gynt.
--- DateTime: 28/11/2021 21:20
---

local yaml = require('vendor.yaml.yaml')

local namespace = {}

namespace.eval = function(yml)
    yml = yml:gsub("\n +$", "\n")
    return yaml.eval(yml)
end

namespace.oriEval = yaml.eval

return namespace