---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gynt.
--- DateTime: 28/11/2021 21:20
---

local yaml = require('vendor.yaml.yaml')

local namespace = {}

namespace.eval = function(yml)
    if yml:len() == 0 then
        return { }
    end
    yml = yml:gsub("\n +$", "")
    yml = yml .. "\n"
    local success, result = pcall(function() return yaml.eval(yml) end)
    if success then
        return result
    else
        return nil, result -- result is an error message
    end
end

namespace.oriEval = yaml.eval

return namespace