---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gynt.
--- DateTime: 12/12/2021 19:56
---


return {

    init = function(self, config)

    end,

    enable = function(self, config)

        local infoLocation = core.AOBScan("0f bf 86 ? ? ? ? 3b c3 0f 84 b3 00 00 00 8b e8 8b 86 ? ? ? ? 69 ed 90 04 00 00 3b 85 ? ? ? ? 0f 85 94 00 00 00 0f bf 8d ? ? ? ? 0f bf 95 ? ? ? ? 0f bf 86 ? ? ? ? 51 0f bf 8e ? ? ? ? 52 50 51 b9 ? ? ? ? e8 ? ? ? ?")

        local targetedUnitID = core.readInteger(infoLocation + 3)
        local successLocation = core.readInteger(infoLocation + 9 + 2) + infoLocation + 9 + 6
        local currentYPosition = core.readInteger(infoLocation + 41 + 3)
        local currentXPosition = core.readInteger(infoLocation + 48 + 3)
        local workTimer = currentXPosition + 0x224 --TODO if necessary, cmp with workTimer and just return home after a while...

        ---This function does a rectangle based distance calculation
        local distFuncECX = core.readInteger(infoLocation + 73 + 1)
        local distFunc = core.readInteger(infoLocation + 78 + 1) + (infoLocation + 78) + 5

        local hookLocation = infoLocation + 35
        local returnLocation = hookLocation + 6


        local addedCode = [[

        virtual at ebp
          targetedUnitOffset dd ?
        end virtual

        virtual at esi
          currentUnitOffset dd ?
        end virtual

        ; do the original jump first
        jnz successLocation ; original code

        ; check if the target unit is too far...
        movsx eax, word [targetedUnitOffset + currentYPosition]
        push eax
        movsx eax, word [targetedUnitOffset + currentXPosition]
        push eax
        movsx eax, word [currentUnitOffset + currentYPosition]
        push eax
        movsx eax, word [currentUnitOffset + currentXPosition]
        push eax
        mov ecx, distFuncECX
        call distFunc

        cmp eax, 40
        jg successLocation

        ;je returnLocation

        ]]

        core.insertCode(
                hookLocation,
                6,
                {core.AssemblyLambda(addedCode, {
                    distFunc = distFunc,
                    distFuncECX = distFuncECX,
                    successLocation = successLocation,
                    currentXPosition = currentXPosition,
                    currentYPosition = currentYPosition,
                    -- returnLocation = returnLocation
                })})

    end,

    disable = function(self, config)
        error("not implemented")
    end
}