



CONST_DEFAULT_CONFIG_FILE = "ucp-config.yml"
CONST_UCP_FOLDERNAME = "ucp/"
BASEDIR = CONST_UCP_FOLDERNAME
CONST_PLUGINS_FOLDER = CONST_UCP_FOLDERNAME .. "plugins/"
CONST_MODULES_FOLDER = CONST_UCP_FOLDERNAME .. "modules/"

CONST_ENV_UCP_CONFIG = "UCP_CONFIG"

CONST_FINAL_CONFIG_CACHE_FILE = CONST_UCP_FOLDERNAME .. ".ucp-final-config-cache"

CONST_CODE_FOLDER = CONST_UCP_FOLDERNAME .. "code/"
CONST_DEVCODE_PATH = CONST_CODE_FOLDER .. "dev.lua"

CONST_INIT_FILE = "init.lua"
CONST_OPTIONS_FILE = "options.yml"
CONST_CONFIG_FILE = "config.yml"
CONST_DEFINITION_FILE = "definition.yml"